M48
; DRILL file {KiCad 9.0.2} date 2026-05-26T23:11:12-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-26T23:11:12-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X65.925Y19.115
X65.925Y13.335
T2
X6.0Y31.0
X6.0Y6.0
X67.0Y31.0
X67.0Y6.0
M30
